# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: How to use
  items:
    - label: 'プロフィールを作ろう'
      link: '/howtouse/profile'
    - label: 'ビデオチャットに参加しよう'
      link: '/howtouse/broadcast'
- label: More
  items:
    - label: 利用規約とプライバシー
      link: /privacy
    - label: 'Twitter'
      link: https://twitter.com/votepurchase
