# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: How to use
  items:
    - label: 'プロフィールを作ろう'
      link: '/howtouse/profile'
    - label: 'ビデオチャットに参加しよう'
      link: '/howtouse/broadcast'
    - label: 'つながりを作ろう'
      link: '/howtouse/connection'
- label: More
  items:
    - label: 利用規約とプライバシー
      link: /privacy
    - label: 'Twitter'
      link: https://twitter.com/votepurchase
    - label: 'Google Play'
      link: https://play.google.com/store/apps/details?id=net.votepurchase.ocacatalk